### PR TITLE
added props to manipulate columns and add filters if needed

### PR DESCRIPTION
**Pull request by Abhay-soni-developer**

### CODE REVIEW

**Comment by Abhay-soni-developer** [comment]
@deepan10  we need to manipulate the columns of the table as per our requirements and we also need filters, so I have contributed to this plugin the needed functionality these are very generic features and may be required by even more users so can we get this merge to the main codebase.

you can give feedback and reviews if you want us to do something more before you can merge this PR.

Regards 
Abhay soni
abhaysoni.developer@gmail.com

**Comment by deepan10** [comment]
Thank you for contributing. I have some review comments.

**Comment by Abhay-soni-developer** [comment]
please post your reviews so i can work over them.

**Comment by deepan10** [comment]
@Abhay-soni-developer  
Its already here https://github.com/deepan10/backstage-plugin-blackduck/pull/1/files/9614540879e7e216781afb3f2b5f22b595d207e6

**Comment by Abhay-soni-developer** [comment]
@deepan10  i can not see your feedbacks, lets connect directly to sort this out and move things fastly

**Pull request merged**
